# Generated by Django 3.2.6 on 2021-08-14 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graph', '0002_auto_20210815_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vertex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VID', models.IntegerField()),
                ('description', models.TextField()),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.graph')),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('vertex_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcoming_edges', to='graph.vertex')),
                ('vertex_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='graph.vertex')),
            ],
        ),
    ]
