# Generated by Django 3.2.6 on 2021-08-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_edge_graph_vertex'),
    ]

    operations = [
        migrations.AddField(
            model_name='vertex',
            name='name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
