# Generated by Django 3.2.6 on 2021-08-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0005_auto_20210815_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='graph',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vertex',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
