# Generated by Django 3.2.6 on 2021-08-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0007_auto_20210816_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='graphs/'),
        ),
    ]
