# Generated by Django 3.2.6 on 2021-09-28 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0008_graph_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edge',
            options={'ordering': ['source__VID', 'target__VID']},
        ),
        migrations.AlterModelOptions(
            name='vertex',
            options={'ordering': ['VID']},
        ),
    ]
