# Generated by Django 3.2.6 on 2021-09-29 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategy',
            old_name='problem_formulation',
            new_name='problem',
        ),
    ]
